name: mothersbd
description: A new Flutter project.

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.3.1
  double_back_to_close_app: ^2.0.1
  fluttertoast: ^8.0.8
  animations: ^2.0.2
  google_sign_in: ^6.0.2
  lottie: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "my_icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/
    - assets/my_icon.png
  uses-material-design: true

